# fly.toml app configuration file generated on 2025-06-14T22:36:04+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
